### ISSUE TITLE
发布HelloServer例子失败

### ISSUE THREAD

**Issue by tangramor** [Tencent/Tars#169]
按C++的HelloServer例子来的，发布的时候出错
![qq 20180202160240](https://user-images.githubusercontent.com/491287/35722857-f61ed3a2-0832-11e8-9c82-1de2d01dde74.png)

日志报：
2018-02-02 16:03:11.340|INFO|AdminService.java|133|lambda$addTask$1|item=050c9a275d1a48138a80b8d75d713f36, applicaiton=TestApp, server_name=HelloServer, node_name=172.17.0.4, command=patch_tars, parameters={patch_id=52, bak_flag=0, update_text=}
2018-02-02 16:03:11.354|INFO|WrappedController.java|83|handleException|exception intercepted, uri=/pages/server/api/add_task, isajax=true
com.qq.tars.rpc.exc.ClientException: tars.tarsregistry.QueryObj|connect failed to 172.17.0.4:17890
	at com.qq.tars.client.ObjectProxy.invoke(ObjectProxy.java:101)
	at com.sun.proxy.$Proxy151.findObjectByIdInSameGroup(Unknown Source)
	at com.qq.tars.support.query.QueryHelper.getServerNodes(QueryHelper.java:57)
	at com.qq.tars.client.ObjectProxyFactory.updateServantEndpoints(ObjectProxyFactory.java:124)
	at com.qq.tars.client.ObjectProxyFactory.getObjectProxy(ObjectProxyFactory.java:53)
	at com.qq.tars.client.ServantProxyFactory.getServantProxy(ServantProxyFactory.java:46)
	at com.qq.tars.client.Communicator.stringToProxy(Communicator.java:78)
	at com.qq.tars.client.Communicator.stringToProxy(Communicator.java:61)
	at com.qq.tars.service.admin.AdminService.getAdminRegPrx(AdminService.java:63)
	at com.qq.tars.service.admin.AdminService.addTask(AdminService.java:139)
	at com.qq.tars.service.task.TaskService.addTask(TaskService.java:76)
	at com.qq.tars.web.controller.TaskController.addTask(TaskController.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:159)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:97)
	at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:98)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
	at com.qq.tars.web.filter.WrapRequestFilter.doFilter(WrapRequestFilter.java:32)
	at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
	at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:156)
	at com.caucho.server.webapp.AccessLogFilterChain.doFilter(AccessLogFilterChain.java:95)
	at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:290)
	at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:838)
	at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:1353)
	at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:1309)
	at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:1293)
	at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:1201)
	at com.caucho.network.listen.TcpSocketLink.handleAcceptTaskImpl(TcpSocketLink.java:997)
	at com.caucho.network.listen.ConnectionTask.runThread(ConnectionTask.java:117)
	at com.caucho.network.listen.ConnectionTask.run(ConnectionTask.java:93)
	at com.caucho.network.listen.SocketLinkThreadLauncher.handleTasks(SocketLinkThreadLauncher.java:169)
	at com.caucho.network.listen.TcpSocketAcceptThread.run(TcpSocketAcceptThread.java:61)
	at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
	at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
Caused by: com.qq.tars.rpc.exc.NotConnectedException: connect failed to 172.17.0.4:17890
	at com.qq.tars.client.rpc.ServantClient.reConnect(ServantClient.java:115)
	at com.qq.tars.client.rpc.ServantClient.ensureConnected(ServantClient.java:124)
	at com.qq.tars.client.rpc.ServantClient.invokeWithSync(ServantClient.java:132)
	at com.qq.tars.client.rpc.tars.TarsInvoker.invokeWithSync(TarsInvoker.java:114)
	at com.qq.tars.client.rpc.tars.TarsInvoker.doInvokeServant(TarsInvoker.java:63)
	at com.qq.tars.client.rpc.ServantInvoker.doInvoke(ServantInvoker.java:44)
	at com.qq.tars.rpc.common.support.AbstractInvoker.invoke(AbstractInvoker.java:75)
	at com.qq.tars.client.ObjectProxy.invoke(ObjectProxy.java:92)
	... 49 more
2018-02-02 16:03:15.755|INFO|ConfigService.java|190|deleteUnusedNodeConfigFiles|delete 0 unused node config file(s)

多点两遍发布按钮，错误又不一样了：
![qq 20180202160703](https://user-images.githubusercontent.com/491287/35722921-430ab988-0833-11e8-9094-0016fb36a116.png)

2018-02-02 16:04:22.640|INFO|AdminService.java|133|lambda$addTask$1|item=161d0170880247f8b957e0f732f69336, applicaiton=TestApp, server_name=HelloServer, node_name=172.17.0.4, command=patch_tars, parameters={patch_id=52, bak_flag=0, update_text=}
2018-02-02 16:04:22.655|INFO|WrappedController.java|83|handleException|exception intercepted, uri=/pages/server/api/add_task, isajax=true
com.qq.tars.rpc.exc.NoConnectionException: tars.tarsregistry.QueryObj|tars.tarsregistry.QueryObj try to select active invoker, size=2, no such active connection invoker
	at com.qq.tars.client.ObjectProxy.invoke(ObjectProxy.java:99)
	at com.sun.proxy.$Proxy151.findObjectByIdInSameGroup(Unknown Source)
	at com.qq.tars.support.query.QueryHelper.getServerNodes(QueryHelper.java:57)
	at com.qq.tars.client.ObjectProxyFactory.updateServantEndpoints(ObjectProxyFactory.java:124)
	at com.qq.tars.client.ObjectProxyFactory.getObjectProxy(ObjectProxyFactory.java:53)
	at com.qq.tars.client.ServantProxyFactory.getServantProxy(ServantProxyFactory.java:46)
	at com.qq.tars.client.Communicator.stringToProxy(Communicator.java:78)
	at com.qq.tars.client.Communicator.stringToProxy(Communicator.java:61)
	at com.qq.tars.service.admin.AdminService.getAdminRegPrx(AdminService.java:63)
	at com.qq.tars.service.admin.AdminService.addTask(AdminService.java:139)
	at com.qq.tars.service.task.TaskService.addTask(TaskService.java:76)
	at com.qq.tars.web.controller.TaskController.addTask(TaskController.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:159)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:97)
	at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:98)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
	at com.qq.tars.web.filter.WrapRequestFilter.doFilter(WrapRequestFilter.java:32)
	at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
	at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:156)
	at com.caucho.server.webapp.AccessLogFilterChain.doFilter(AccessLogFilterChain.java:95)
	at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:290)
	at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:838)
	at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:1353)
	at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:1309)
	at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:1293)
	at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:1201)
	at com.caucho.network.listen.TcpSocketLink.handleAcceptTaskImpl(TcpSocketLink.java:997)
	at com.caucho.network.listen.ConnectionTask.runThread(ConnectionTask.java:117)
	at com.caucho.network.listen.ConnectionTask.run(ConnectionTask.java:93)
	at com.caucho.network.listen.SocketLinkThreadLauncher.handleTasks(SocketLinkThreadLauncher.java:169)
	at com.caucho.network.listen.TcpSocketAcceptThread.run(TcpSocketAcceptThread.java:61)
	at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
	at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
Caused by: com.qq.tars.rpc.common.exc.NoInvokerException: tars.tarsregistry.QueryObj try to select active invoker, size=2, no such active connection invoker
	at com.qq.tars.client.rpc.loadbalance.RoundRobinLoadBalance.select(RoundRobinLoadBalance.java:93)
	at com.qq.tars.client.rpc.loadbalance.DefaultLoadBalance.select(DefaultLoadBalance.java:78)
	at com.qq.tars.client.ObjectProxy.invoke(ObjectProxy.java:91)
	... 49 more

**Comment by tangramor** [comment]
抱歉第一个截图错了，应该是 com.qq.tars.rpc.exc.ClientException: tars.tarsregistry.QueryObj|connect failed to 172.17.0.4:17890 这个错的

**Comment by tangramor** [comment]
是registry 服务没起来的原因，运行 ps -ef | grep tarsreg 可以查看是否有此进程
