### ISSUE TITLE
PHPClient 使用指定 ip 的方式调用服务问题

### ISSUE THREAD

**Issue by ZhengChuHai** [Tencent/Tars#212]
测试代码：
```php
<?php
  require_once("./vendor/autoload.php");

  // 指定主控ip、port
  $config = new \Tars\client\CommunicatorConfig();
  $config->setLocator('PHPTest.PHPServer.obj@tcp -h 172.17.0.10 -p 10010');
  $config->setSocketMode(1);
  $route['sIp']="172.17.0.10";
  $route['iPort']=10010;
  $routeInfo[]=$route;
  $config->setRouteInfo($routeInfo);

  $servant = new Client\servant\PHPTest\PHPServer\obj\TestTafServiceServant($config);

  $name = 'test';
  $intVal = $servant->sayHelloWorld($name, $greetings);

  echo '<p>'.$greetings.'</p>';
```
发生以下错误：
```
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgHead::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgHead.php on line 91
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgBody::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgBody.php on line 63
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgHead::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgHead.php on line 91
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgBody::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgBody.php on line 63
PHP Notice:  Undefined offset: 0 in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 54
PHP Notice:  Undefined offset: 0 in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 55
PHP Warning:  socket_connect(): Host lookup failed [-10003]: Unknown server error in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 90
monitorStat failed
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgHead::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgHead.php on line 91
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgBody::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgBody.php on line 63
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgHead::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgHead.php on line 91
PHP Notice:  Accessing static property Tars\monitor\classes\StatMicMsgBody::$__fields as non static in /data/web/client/vendor/phptars/tars-monitor/src/classes/StatMicMsgBody.php on line 63
PHP Notice:  Undefined offset: -1 in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 54
PHP Notice:  Undefined offset: -1 in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 55
PHP Warning:  socket_connect(): Host lookup failed [-10003]: Unknown server error in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 90
monitorStat failed
PHP Fatal error:  Uncaught Exception in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php:92
Stack trace:
#0 /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php(61): Tars\monitor\client\CommunicatorMonitor->socketTcp(NULL, NULL, '\x00\x00\x00\xC2\x10\x03,<@\x01V\x15tar...', 2)
#1 /data/web/client/vendor/phptars/tars-monitor/src/StatFServant.php(51): Tars\monitor\client\CommunicatorMonitor->invoke(Object(Tars\monitor\client\RequestPacketMonitor), 2)
#2 /data/web/client/vendor/phptars/tars-monitor/src/StatFWrapper.php(139): Tars\monitor\StatFServant->reportMicMsg(Array, true)
#3 /data/web/client/vendor/phptars/tars-monitor/src/StatFWrapper.php(127): Tars\monitor\StatFWrapper->reportMicMsg(Array, true)
#4 /data/web/client/vendor/phptars/tars-client/src/Communicator.php(144): Tars\monitor\StatFWrapper->monitorStat('PHPTest.PHPServ...', 'sayHelloWorld', '172.17.0.10', 10010, 3, 0, 0)
#5 /data/web/client/PHPTest/PHPServer/obj/TestTafServiceServant.php(84): Tars\client\Communi in /data/web/client/vendor/phptars/tars-monitor/src/client/CommunicatorMonitor.php on line 92
```
跟踪发现，在执行/data/web/client/vendor/phptars/tars-client/src/Communicator.php的 invoke 方法会执行3次，第一次能正常取到 IP 跟 port ，后面的都为 null

**Comment by meijing0114** [comment]
在最新的commit中，已经修复问题，原因是tars-client中对locator未指定的情况判断不充分。
